# Generated by Django 5.2.15 on 2026-08-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_code', models.CharField(max_length=50, unique=True, verbose_name='网站代码')),
                ('interval_minutes', models.PositiveIntegerField(default=60, verbose_name='爬取间隔(分钟)')),
                ('is_scheduled_enabled', models.BooleanField(default=True, verbose_name='启用定时')),
                ('last_scheduled_run_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_code', models.CharField(max_length=50, verbose_name='网站代码')),
                ('trigger_type', models.CharField(choices=[('scheduled', '定时'), ('manual', '手动')], max_length=10, verbose_name='触发方式')),
                ('pid', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('stopped', '已停止')], default='pending', max_length=15, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('items_found', models.PositiveIntegerField(default=0, verbose_name='采集条数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
