# Generated by Django 5.2.15 on 2026-08-18 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网站名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='唯一代码')),
                ('url', models.URLField(max_length=500, verbose_name='主页地址')),
                ('category', models.CharField(choices=[('government', '政府采购'), ('finance', '金融集采'), ('province', '省公共资源'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('requires_login', models.BooleanField(default=False, verbose_name='需登录')),
                ('crawl_interval', models.PositiveIntegerField(default=60, verbose_name='爬取间隔(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FilterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('keywords', models.TextField(blank=True, verbose_name='包含关键词(逗号分隔)')),
                ('exclude_keywords', models.TextField(blank=True, verbose_name='排除关键词(逗号分隔)')),
                ('regions', models.TextField(blank=True, verbose_name='地区(逗号分隔)')),
                ('industries', models.TextField(blank=True, verbose_name='行业(逗号分隔)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BiddingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('source_url', models.URLField(max_length=1000, verbose_name='原始链接')),
                ('source_unique_id', models.CharField(max_length=200, verbose_name='去重键')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('purchaser', models.CharField(blank=True, max_length=300, verbose_name='招标人/采购人')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='地区')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='行业分类')),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='预算金额(元)')),
                ('bid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='中标金额(元)')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('content', models.TextField(blank=True, verbose_name='公告正文')),
                ('contact_info', models.TextField(blank=True, verbose_name='联系方式')),
                ('attachment_url', models.URLField(blank=True, max_length=1000, verbose_name='附件地址')),
                ('status', models.CharField(choices=[('open', '招标中'), ('closed', '已截止'), ('awarded', '已中标')], default='open', max_length=20, verbose_name='状态')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='bidding.biddingwebsite', verbose_name='来源网站')),
            ],
            options={
                'ordering': ['-publish_date', '-created_at'],
                'indexes': [models.Index(fields=['publish_date'], name='bidding_bid_publish_0cf81e_idx'), models.Index(fields=['region'], name='bidding_bid_region_4cf859_idx'), models.Index(fields=['industry'], name='bidding_bid_industr_b976d9_idx')],
                'unique_together': {('website', 'source_unique_id')},
            },
        ),
    ]
