# Generated by Django 5.2.15 on 2026-08-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddinginfo',
            name='project_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='项目编号'),
        ),
    ]
